import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outfile = prod
  ? "obsidian-share-by-hackmd/main.js"  // build 模式輸出到本地 dist/
  : "C:\\Users\\jx06t\\iCloudDrive\\iCloud~md~obsidian\\jx\\.obsidian\\plugins\\obsidian-share-by-hackmd\\main.js";  // dev 模式輸出到 Obsidian plugin 資料夾

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	// outfile: "D:\\Document_J\\iCloudDrive\\iCloud~md~obsidian\\jx\\.obsidian\\plugins\\obsidian-share-by-hackmd\\main.js",
	// outfile: "C:\\Users\\jx06t\\iCloudDrive\\iCloud~md~obsidian\\jx\\.obsidian\\plugins\\obsidian-share-by-hackmd\\main.js",
	// outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}